# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# React Native Architecture
newArchEnabled=false

# Hermes JS Engine
hermesEnabled=true

# Memory and Build Cache
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
